/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class haiidea_com_myopencv_utils_NdkUtil */

#ifndef _Included_haiidea_com_myopencv_utils_NdkUtil
#define _Included_haiidea_com_myopencv_utils_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     haiidea_com_myopencv_utils_NdkUtil
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_haiidea_com_myopencv_utils_NdkUtil_gray
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     haiidea_com_myopencv_utils_NdkUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_haiidea_com_myopencv_utils_NdkUtil_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
